{{- /* chezmoi:modify-template */ -}}
{{ .chezmoi.stdin | fromToml | setValueAtPath "analytics.enabled" false | setValueAtPath "features.memories" false | setValueAtPath "memories.generate_memories" false | setValueAtPath "memories.use_memories" false | setValueAtPath "memories.disable_on_external_context" true | toToml }}
